jdbcFBUrl = "jdbc:facebook:"
pageId = "ADD_PAGE_ID"
InitiateOAuth = "OFF"
appId = "ADD_APP_ID"
appSecret = "ADD_APP_SECRET"
pageAccessToken = "ADD_PAGE_ACCESS_TOKEN"
capacity = "ADD_CACHE_CAPACITY"
evictionFactor = "ADD_CACHE_EVICTION_FACTOR"
defaultMaxAge = "ADD_CACHE_DEFAULT_MAX_AGE"
cleanupInterval = "ADD_CACHE_CLEANUP_INTERVAL"
